### ISSUE TITLE
Code grabs incorrect values

### ISSUE THREAD

**Issue by Draco18s** [fxbonnet/unread-count-for-outlook#1]
Because it loops over all spans finding the first one with a numerical values, it finds values such as:

 - Number of Deleted Items
 - Number of emails in Spam
 - Number of emails in a Group
 - Number of attachments on an open email

Right now it's telling me I have 46 unread items. I have no idea where it's getting this number. I have 1 deleted, 126 in a group (which is basically every meeting invite I've ever gotten for 3 years), an open email with 1 attachment.

When I first installed it, it grabbed spam (until I hid folders) then it grabbed the 126 (until I hid groups), now it's just being wack. Running the code in the console the only value it can find is the number of attachments in an open email.

**Comment by fxbonnet** [comment]
Thanks for the feedback @Draco18s 
You are right, it loops over spans and picks up the first one that contains a numeric value. If there are unread messages in your inbox this will be the number that comes first but if you have no unread message in your inbox but have folders with unread messages it might pick these numbers.
I did not find a better way to do that as there is no id we can rely on, also the label "Inbox" depends on user language so it cannot be used either. Any idea?

**Comment by fxbonnet** [comment]
Could 46 be the number of notifications you have on the top right of the page?

**Comment by Draco18s** [comment]
Ah, notifications, yes it grabbed that number at one point too.

But in this case, no. I cleared those out also.

In terms of how to target the right thing... :\

**Comment by fxbonnet** [comment]
Interesting, today I am getting a '1' unread count but I don't know where it comes from. This needs further investigation.

**Comment by fxbonnet** [comment]
I have noticed that inbox has an icon that looks like `<i data-icon-name="Inbox"` at least on outlook.live.com not sure it works the same on other Outlook instances/versions.
@Draco18s could you check if you have the same tag for the icon on your instance?
I have already implemented the changes and pushed to master (but not released on the store yet) if you want to test.

**Comment by Draco18s** [comment]
Looks consistent with my web inbox:

```html
<div class="qDw7SZ9r6S7r0_qZS1aIG _1XmKWz3L5NcheRkx38wxTL NJVykX0WljoRws2qTYI5G" data-is-focusable="true" title="Inbox" role="treeitem" aria-selected="true" aria-level="2" style="padding-left: 0px; padding-right: 28px;" tabindex="0">
    <i data-icon-name="Inbox" aria-hidden="true" class="_1IolX_6rKX93IRLO1O_oCP _1OPSsVxfk_GWTnwo-KIMYX root-61"></i>
    <span class="_16aPYHYIOVxzNYTA4BGnwS _1XmKWz3L5NcheRkx38wxTL NJVykX0WljoRws2qTYI5G _3FwRpWCSns-2PgbiDhEErG">Inbox</span>
    <span class="_3Jn_7Iv4SwMTMOPJiydZLa"></span>
</div>

**Comment by fxbonnet** [comment]
Thanks for checking @Draco18s 
The new version has just been released on Chrome web store. Can you update to version 1.9 and check that it is working as expected?

**Comment by Draco18s** [comment]
Sorry, been meaning to get back to this. I installed the updated version and haven't been getting the unread count *at all.*

It might be a "restart browser" problem and usually IT applies updates Windows once a week (i.e. a forced restart) and I was waiting for that to happen, but it hasn't. I'll restart manually today and do some investigation.

**Comment by Draco18s** [comment]
Update: yep, just needed to reload the web page. Looks like it's working now. 👍

**Comment by lizyn** [comment]
@fxbonnet This is happening to me again. In my case, the code picks the first folder with an unread count. In the following example, it will use the count of the draft folder.

![image](https://github.com/fxbonnet/unread-count-for-outlook/assets/26119970/94ffb6d8-d91d-46c0-b625-98d0a184bda7)

I think the reason is that Outlook has changed the data-icon-name. For me, it's now "MailInboxRegular".

```
<i data-icon-name="MailInboxRegular" aria-hidden="true" class="jgnYx LPIso SuSxc MgbmD root-90"><span role="presentation" aria-hidden="true" class="FLwLv"><i class="Q0K3G ___198tor0 f14t3ns0 fne0op0 fg4l7m0 fmd4ok8 f1sxfq9t" fill="currentColor" aria-hidden="true"></i></span></i>
```

> https://github.com/fxbonnet/unread-count-for-outlook/issues/1#issuecomment-826499202 I have noticed that inbox has an icon that looks like `<i data-icon-name="Inbox"` at least on outlook.live.com not sure it works the same on other Outlook instances/versions. @Draco18s could you check if you have the same tag for the icon on your instance? I have already implemented the changes and pushed to master (but not released on the store yet) if you want to test.

**Comment by fxbonnet** [comment]
Interesting. Thanks for the details @lizyn 
Is there any other tag with  data-icon-name containing "inbox"? Maybe searching for a value containing "inbox" rather than an exact value would be more robust. Unfortunately Microsoft can decide to change the html at any time without notice

**Comment by lizyn** [comment]
Yes that's a good idea @fxbonnet . On my side, XPath `//*[contains(@data-icon-name, 'Inbox')]` only gives me one result, which is exactly the inbox sector, and the lowercase version `//*[contains(@data-icon-name, 'inbox')]` (note it's **i** not **I**) gives me nothing.

**Comment by lizyn** [comment]
I made a PR for this #2 , can you take a look at it?

**Comment by fxbonnet** [comment]
Thank you. I have merged the PR.
I have submitted the new package but it may take a few day for it to be reviewed and published. I will keep you posted.

**Comment by fxbonnet** [comment]
Actually it was faster than expected. The new version (3.0) has just been published and all users should get the upgrade automatically very soon.
